version: '3'
services:

  redis:
    networks:
      - net_test
    container_name: redis
    image: redis:7.2.4
    volumes:
      - ./redis-data:/data

  server:
    networks:
      - net_test
    container_name: server
    image: golang:1.22.0
    working_dir: /go/server
    volumes:
      - ./server/:/go/server
    # entrypoint: go run .
    entrypoint: go test -v ./...
    ports:
      - "80:80"
    depends_on:
      - redis
      

networks:
  net_test: